name: Laravel CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, pdo_sqlite, dom, curl, fileinfo, json
          coverage: none

      - name: Copiar .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Composer install (cahed)
        uses: ramsey/composer-install@v2
        with:
          composer-options: --no-progress --prefer-dist --optimize-autoloader

      - name: Crear base SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Migraciones
        run: php artisan migrate --force

      - name: Ejecutar pruebas
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test -q